databases:
  - name: backend
    databaseName: backend
    user: backend
    plan: free

services:
  - type: web
    name: backend
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
