name: Rails Tests

on:
  pull_request:
    branches: [ "main" ] # Or your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD:
          POSTGRES_DB: backend_test
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2' # Or your ruby version
        bundler-cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' #Or your Node version

    - name: Install dependencies
      run: |
        cd backend
        bundle install
        yarn install

    - name: Set up database
      run: |
        cd backend
        bundle exec rails db:create db:migrate

    - name: Run tests
      run: |
        cd backend
        bundle exec rake test
